### ISSUE TITLE
🐛[BUG]: No module named 'pysdf'

### ISSUE THREAD

**Issue by YouqiongLiu** [NVIDIA/modulus-sym#103]
### Version

nvidia-modulus： 0.4.0    nvidia-modulus.sym：1.2.0

### On which installation method(s) does this occur?

Pip

### Describe the issue

installed the latest version of  nvidia-modulus.sym is using PyPi.
But,  the following programs cannot be run . Error importing pysdf. Make sure 'libsdf.so' is in LD_LIBRARY_PATH and pysdf is installed

import os
import warnings
import torch
import numpy as np
from sympy import Symbol, sqrt, Max

import modulus.sym
from modulus.sym.geometry.tessellation import Tessellation

### Minimum reproducible example

```shell
import os
import warnings
import torch
import numpy as np
from sympy import Symbol, sqrt, Max

import modulus.sym
from modulus.sym.geometry.tessellation import Tessellation
```

### Relevant log output

```shell
Error importing pysdf. Make sure 'libsdf.so' is in LD_LIBRARY_PATH and pysdf is installed
--------------------------------------------------------------------------- ModuleNotFoundError Traceback (most recent call last) /home/wangtai/youqiongliu/pinn-blood-flow-main/examples/cylinder/test.py in line 1 ----> 26 from modulus.sym.geometry.tessellation import Tessellation File ~/anaconda3/envs/python3.10_pytorch2.1/lib/python3.10/site-packages/modulus/sym/geometry/tessellation.py:25 22 from sympy import Symbol 24 try: ---> 25 import pysdf.sdf as pysdf 26 except: 27 print( 28 "Error importing pysdf. Make sure 'libsdf.so' is in LD_LIBRARY_PATH and pysdf is installed" 29 ) ModuleNotFoundError: No module named 'pysdf'
```

**Comment by ktangsali** [comment]
@YouqiongLiu, pysdf is currently available only via Docker container method. Please try the docker method of install as described here: https://github.com/NVIDIA/modulus-sym?tab=readme-ov-file#container to use the STL geometry features.
