### ISSUE TITLE
🐛[BUG]: Incorrect non-dimensionalization in the Chip 2D example

### ISSUE THREAD

**Issue by ram-cherukuri** [NVIDIA/modulus-sym#109]
### Version

1.4.0

### Describe the issue

In the Chip_2D example, in chip_2d_solid_fluid_heat_transfer_heat.py - the non dimensionalizing below is incorrect

nd_copper_source_grad = copper_heat_flux * length_scale / temp_scale 

Looks like final units are W/m^2/m-K  = kg m^2 / s^3 /m^2  /m-K  = kg / s^3 /m-K

This needs to be fixed. Also the idea of non-dimensionalization should be clarified if we are not making some assumptions.

**Comment by ktangsali** [comment]
There seems to be a typo in the example code. The copper_heat_flux is actually in dT/dx format, hence the Flux is 51.94 K/m (20000 W/m). The subsequent non-dimensionalization is correct. I will open a quick PR to fix this.
