### ISSUE TITLE
A missed term in the navier_stokes equation

### ISSUE THREAD

**Issue by zhangzhen117** [NVIDIA/modulus-sym#22]
Hi, there is a term missed in the Navier-Stokes equation, i.e. mu__x_j*u_j__x_i for the i th momentum equation.
    >>> ns = NavierStokes(nu='nu', rho=1, dim=2, time=False)
    >>> ns.pprint()
the result should be:
continuity: 1.0*u__x + 1.0*v__y
momentum_x: -1.0*nu*u__x__x - 1.0*nu*u__y__y + 1.0*u*u__x + 1.0*v*u__y - 2.0*nu__x*u__x - 1.0*nu__y*u__y - 1.0*nu__y*v__x + p__x
momentum_y: -1.0*nu*v__x__x - 1.0*nu*v__y__y + 1.0*u*v__x + 1.0*v*v__y - 1.0*nu__x*u__y - 1.0*nu__x*v__x - 2.0*nu__y*v__y + p__y
instead of:
continuity: u__x + v__y
momentum_x: -nu*u__x__x - nu*u__y__y + u*u__x + v*u__y - nu__x*u__x - nu__y*u__y + p__x
momentum_y: -nu*v__x__x - nu*v__y__y + u*v__x + v*v__y - nu__x*v__x - nu__y*v__y + p__y

**Comment by misawann** [comment]
I think the following term, for example in momentum_x, is missing in the implementation, which is consistent of the above comment in the 2D case.

![image](https://github.com/NVIDIA/modulus-sym/assets/63899839/c2bb16fc-778c-4b62-af3c-8aee4d76ab80)
The implementation might be changed like this;
```
self.equations["momentum_x"] = (
    (rho * u).diff(t)
    + (
    u * ((rho * u).diff(x))
    + v * ((rho * u).diff(y))
    + w * ((rho * u).diff(z))
    + rho * u * (curl)
    )
    + p.diff(x)
    - (-2 / 3 * mu * (curl)).diff(x)
    - (mu * u.diff(x)).diff(x)
    - (mu * u.diff(y)).diff(y)
    - (mu * u.diff(z)).diff(z)
    - (mu * (curl).diff(x))
    # missing terms
    - mu.diff(x) * u.diff(x)
    - mu.diff(y) * v.diff(x)
    - mu.diff(z) * w.diff(x)
)
```

**Comment by zhangzhen117** [comment]
Yes, I think you are correct.

**Comment by misawann** [comment]
Thank you. I opened a PR.

**Comment by ktangsali** [comment]
Thanks for the issue report and the PR. The team is looking into it and will get back soon.
