### ISSUE TITLE
openfoam data missing?

### ISSUE THREAD

**Issue by janticev** [NVIDIA/modulus-sym#28]
I'm not seeing any of the openfoam validation data for the examples when cloning from this repo. It works properly with git-lfs when I go clone it again from the older 22.09 gitlab source, but not here. Did it move?

**Comment by NickGeneva** [comment]
Hi @janticev 

Many data files can be downloaded here:
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/modulus/resources/modulus_sym_examples_supplemental_materials/files

We removed these from the repo to keep the clone size small.

**Comment by janticev** [comment]
Thanks!
