### ISSUE TITLE
Can modulus be used to solve ODE?

### ISSUE THREAD

**Issue by gaowutong** [NVIDIA/modulus-sym#37]
In modulus, usually a geometry object is defined to represent the space domain of the PDE. The constraints are then defined by passing geometry. What if I want to solve a ODE? It seems I can not define such a trajectory geometry in advance because it is to be solved. Any examples about ODE?

**Comment by NickGeneva** [comment]
Hi @gaowutong 

Solving an ODE should be certainly possible and is likely a simplification of many of the implemented examples. Solving a simple spring mass ODE system can be found in our [documentation](https://docs.nvidia.com/deeplearning/modulus/modulus-sym/user_guide/foundational/ode_spring_mass.html). Additional other have worked on solving different ODEs in our [forums](https://forums.developer.nvidia.com/t/parametrization-of-an-ode-coefficient/253729).

**Comment by gaowutong** [comment]
@NickGeneva Thanks for the kind response! I'm going to try to solve some ODEs of my domain using modulus.
