### ISSUE TITLE
📚[DOC]: How to get pysdf and build Docker container with it 

### ISSUE THREAD

**Issue by michaltakac** [NVIDIA/modulus-sym#52]
### How would you describe the priority of this documentation request

Critical (currently preventing usage)

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

In the readme, I see 
```
git clone <internal pysdf repo>
```
step. But where is the pysdf repo we should use?

We're migrating our infra at Siml.ai from modulus:22.09 to modulus:23:05 and above, but we cannot proceed forward without proper knowledge of how to build the new modulus version in Docker with Tessellation support (we're building our own Docker image using `FROM nvcr.io/nvidia/modulus/modulus:23.05`)

**Comment by HydrogenSulfate** [comment]
Same here, I have no idea why pysdf is not a valid git url, but a weird `<internal pysdf repo>`.

But I have a temporary solution that you can use https://github.com/sxyu/sdf and modify the code about about sdf in `tessellation.py`. I get correct training result in mesh examples except those need `sdf_derivatives` which `sxyu/sdf` can not compute.
