### ISSUE TITLE
🐛[BUG]: can not download dataset for training reservoir_simulation/3D case:

### ISSUE THREAD

**Issue by sangnguyens** [NVIDIA/modulus-sym#59]
### Version

23.08

### On which installation method(s) does this occur?

Pip

### Describe the issue

I have the problem to load dataset from **examples/reservoir_simulation/3D/Forward_problem_PINO.py** as follow:

```
...Downloading Please hold.........
Error executing job with overrides: []
Traceback (most recent call last):
  File "Forward_problem_PINO.py", line 1263, in run
    download_file_from_google_drive(
  File "Forward_problem_PINO.py", line 57, in download_file_from_google_drive
    save_response_content(response, destination)
  File "Forward_problem_PINO.py", line 71, in save_response_content
    with open(destination, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/datausers2/vpi/lnanh/modulus-sym/examples/reservoir_simulation/3D/src/../PACKETS/Training4.mat'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Can you please check the availability of current dataset from google drive?

thanks,
Sang

**Comment by clementetienam** [comment]
Hi,sangnguyens, I just ran the code and could download the dataset, can you please check you are not on a vpn on your work machine?

**Comment by clementetienam** [comment]
Is there a PACKETS folder formed anywhere?

**Comment by clementetienam** [comment]
That is strange. simply download the dataset using the FNO. the same datasets are used for both FNO and PINOa

**Comment by sangnguyens** [comment]
thanks @clementetienam  for your helps. I suppose to close this issue.

**Comment by clementetienam** [comment]
You are welcome. we will update this example with an Inverse methodology workflow to solve reservoir characterisation/History matching.

**Comment by ipe-zhangyz** [comment]
Seems that the bug still exists. I'm using the modulus docker image 24.04 download from NGC, and encounter exactly the same error. what's more, even though I can download the dataset using the FNO case, the dataset file Training4.mat is only 4 KB in size, and the script exits with this error:

```
Load simulated labelled training data from MAT file
Error executing job with overrides: []
Traceback (most recent call last):
  File "Forward_problem_FNO.py", line 798, in run
    matt = sio.loadmat(to_absolute_path("../PACKETS/Training4.mat"))
  File "/home/miniconda3/envs/MDLO/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 226, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/home/miniconda3/envs/MDLO/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
    mjv, mnv = _get_matfile_version(byte_stream)
  File "/home/miniconda3/envs/MDLO/lib/python3.8/site-packages/scipy/io/matlab/_miobase.py", line 251, in _get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 32, 99

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```


There is the same error in both FNO and PINO cases, and in both 2D and 3D cases. And the Training4.mat files downloaded in 2D and 3D cases are both 4.0 KB in size. Maybe the dataset file I downloaded is not the right one?
